Header header

# INPUTS
int32 Decision 
string SceneName
SpatialAtom[] Object
string SupportName
string[] SubClasses
string[] SuperClasses
RetrievalEpisodic retrieval
---

#OUTPUTS
string EpisodicSceneName
bool learnt
SpatialAtom[] EpisodicObject 

