Header header

# INPUTS
int32 Decision 
EpisodicScoreItem Episodic
SemanticScoreItem Semantic
string[] episodicRetrieval
string[] semanticRetrieval
int32 DecisionForgetting  
---

#OUTPUTS
ScoreCounter[] toBeForgottenSemantic
ScoreCounter[] toBeForgottenEpisodic 
ScoreCounter[] lowScoreSemantic 
ScoreCounter[] lowScoreEpisodic
ScoreCounter[] forgotSemantic
ScoreCounter[] forgotEpisodic

