Header header

# INPUTS
int32 Decision 
EpisodicScoreItem Episodic
SemanticScoreItem Semantic
string[] episodicRetrieval
string[] semanticRetrieval 
---

#OUTPUTS
string[] toBeForgottenSemantic
string[] toBeForgottenEpisodic 
string[] lowScoreSemantic 
string[] lowScoreEpisodic
string[] forgotSemantic
string[] forgotEpisodic

